events {
  worker_connections 1024;
}

http {
  upstream web {
    server web:3000;
  }

  upstream parser {
    server parser:3001;
  }

  server {
    listen 80;

    location /api/parse {
      proxy_pass http://parser;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://web;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}